# Generated by Django 2.1.4 on 2018-12-06 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('nome_espaco', models.CharField(max_length=200)),
                ('nome_usuario', models.CharField(max_length=200)),
                ('escala_pixels_centimetros', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obstaculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cor_maxima', models.CharField(max_length=200)),
                ('cor_minima', models.CharField(max_length=200)),
                ('raio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Obstaculo')),
            ],
        ),
        migrations.AddField(
            model_name='configuracao',
            name='objeto_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Obstaculo'),
        ),
    ]
