# Generated by Django 2.1.4 on 2018-12-06 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='objeto',
        ),
        migrations.AddField(
            model_name='log',
            name='obstaculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.Obstaculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='x',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponto',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='obstaculo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ponto', to='core.Obstaculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='objeto_principal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='core.Obstaculo'),
        ),
    ]
